# https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout
# This file is for configuring interactive sessions

# >>> Nix >>>
if [ -e /Users/bogeholm/.nix-profile/etc/profile.d/nix.sh ]; then 
    . /Users/bogeholm/.nix-profile/etc/profile.d/nix.sh; 
fi
# <<< Nix <<<


# >>> Starship >>>
if $(which starship > /dev/null 2>&1); then
    eval "$(starship init zsh)"
fi
# <<< Starship <<<


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/bogeholm/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/bogeholm/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/bogeholm/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/bogeholm/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
